services:
  flea:
    <<: &main
      build:
        context: .
        dockerfile: Dockerfile
      <<: &env
        env_file:
          - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: "always"
    ports:
      - "8000:8000"
    depends_on:
      migrator:
        condition: service_completed_successfully
    volumes:
      - ./app:/docsbox-backend/app
      - ./data/files/:/docsbox-backend/data/files/

  migrator:
    <<: *main
    command: ["alembic", "upgrade", "head"]
    restart: "no"
    depends_on:
      - db

  db:
    <<: *env
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
