"""init

Revision ID: 26b77e774fe3
Revises: 
Create Date: 2025-07-05 23:13:39.557276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26b77e774fe3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False, comment='User ID'),
    sa.Column('email', sa.String(), nullable=False, comment='User email'),
    sa.Column('password', sa.String(), nullable=False, comment='User password hash'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('places',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False, comment='Item ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Item name'),
    sa.Column('parent_uid', sa.Integer(), nullable=True),
    sa.Column('owner_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_uid'], ['users.uid'], name='places_owner_uid_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_uid'], ['places.uid'], name='places_parent_uid_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('sessions',
    sa.Column('refresh_token', sa.String(), nullable=False, comment='Refresh token'),
    sa.Column('csrf_token', sa.String(), nullable=False, comment='CSRF token'),
    sa.Column('user_uid', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Session last refreshed date'),
    sa.Column('ip', postgresql.INET(), nullable=True, comment='IP address'),
    sa.Column('user_agent', sa.String(), nullable=True, comment='User agent'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], name='sessions_user_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refresh_token', name='sessions_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('places')
    op.drop_table('users')
    # ### end Alembic commands ###
