"""init

Revision ID: cbc65d0bc632
Revises:
Create Date: 2025-06-25 19:38:28.618006

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbc65d0bc632'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False, comment='User ID'),
        sa.Column('email', sa.String(), nullable=False, comment='User email'),
        sa.Column('password', sa.String(), nullable=False, comment='User password hash'),
        sa.PrimaryKeyConstraint('uid'),
    )
    op.create_table(
        'sessions',
        sa.Column('refresh_token', sa.String(), nullable=False, comment='Session ID'),
        sa.Column('user_uid', sa.Integer(), nullable=False, comment='User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Session last refreshed date'),
        sa.Column('ip', postgresql.INET(), nullable=True, comment='IP address'),
        sa.Column('user_agent', sa.String(), nullable=True, comment='User agent'),
        sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], name='sessions_user_uid_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('refresh_token', name='sessions_pkey'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
